### PR TITLE
[CRITICAL] Fix issues with incorrect handling of segmentations of certain dimensions

### PR DESCRIPTION
**Pull request by fedorov**
This patch is a cherry-pick of several commits from dcmtk master that fix frame bit encoding that led to incorrect storage of segmentations that generated frame content not aligned at byte boundary (rows*cols not divisible by 8). 

This is a critical update, since DICOM segmentation objects that can be currently created using Slicer interface will not be correct, and correct DICOM objects will not be interpreted/rendered properly for the image dimensions where rows*cols not divisible by 8.

cc @michaelonken

### CODE REVIEW

**Comment by pieper** [comment]
@jcfr will you be merging this?  I can do it if you are already on vacation.

**Comment by fedorov** [comment]
For the reference, as a test of this patch, I did the following:
* compiled Slicer with this patched version of DCMTK on Mac
* confirmed test cases that contain DICOM SEG for the problematic instances are loaded and rendered correctly (based on visual inspection) in Slicer
* confirmed round trip of a DICOM SEG created using Slicer for one of those test cases

**Comment by pieper** [comment]
Since Jc is out I'll go ahead and update slicer to use this version.

**Comment by jcfr** [comment]
Thanks for taking care of this and greetings from Paris.
Jc

**Comment by pieper** [comment]
Have fun Jc!

**Comment by pieper** [comment]
Test build worked for me.  Slicer updated in r24818

**Comment by fedorov** [comment]
Thanks a lot Steve for this quick integration! This will serve as a nice Christmas gift for a few of us ;-)

Happy Holidays to all!

**Pull request merged**
