### PR TITLE
DICOM TR - measurement patches

### PR DESCRIPTION
**Pull request by ihnorton**
I'd like to pull these patches from DCMTK master to fix a few issues with DICOM TR support for along-track measurements.

### CODE REVIEW

**Comment by ihnorton** [comment]
cc @jcfr

**Comment by jcfr** [comment]
:+1: Make sense, I will integrate tomorrow morning

**Comment by fedorov** [comment]
Is there a good reason to use patches, instead of syncing to the latest master?

http://git.dcmtk.org/?p=dcmtk.git;a=summary

**Comment by jcfr** [comment]
> instead of syncing to the latest master?

If we would like to do to a "Slicer 4.10.1" release, cherry-picking patches is more reasonable. The time being, I think it is reasonable to keep that option open.

For reference, the version we currently use is https://github.com/commontk/DCMTK/commits/patched-DCMTK-3.6.3_20180621

**Comment by fedorov** [comment]
> If we would like to do to a "Slicer 4.10.1" release, cherry-picking patches is more reasonable. 

Makes sense. I was thinking to take master, since it will likely have other useful updates (e.g., dictionary updates, like in the latest commit, are just good things to have), and will make the subsequent update of DCMTK easier. But from the perspective of 4.10.1, I agree with you.

**Comment by jcfr** [comment]
Thanks @ihnorton 

commit cherry-picked onto the branch

image

**Comment by jcfr** [comment]
And now integrated in Slicer. See [r27555](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=27555)

**Pull request closed without merging**
