### PR TITLE
Patched dcmtk 3.6.4 20181222

### PR DESCRIPTION
**Pull request by hjmjohnson**
This version of DCMTK builds much more cleanly with C++11 (with respect to warnings).

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@jcfr, @michaelonken  NOTE:  only the last 2 patches are different from the official master branch.  A separate PR was pushed to https://github.com/DCMTK/dcmtk/pull/13

It sure would be nice if Slicer could stop maintaining separate patch sets :).

**Comment by fedorov** [comment]
> It sure would be nice if Slicer could stop maintaining separate patch sets :)

💯 👍 

Considering @jriesmeier [mentioned](https://github.com/DCMTK/dcmtk/pull/13#issuecomment-449592270) that the changes you proposed have been implemented in DMCTK upstream, does it make sense to close this PR, wait until the DCMTK changes show up in the DCMTK public master, and then change the Slicer superbuild to point to the official DCMTK git repo instead of this commontk fork here: https://github.com/DCMTK/dcmtk/pull/13#issuecomment-449592270 ?

**Comment by jriesmeier** [comment]
@fedorov Up to now, I only fixed one issue: the "libtiff without JPEG support" thing. The other proposed changes by @hjmjohnson have to be checked by someone from the DCMTK team who is more familiar with CMake and C++11 - I personally still use GNU Autoconf and "ancient" C++ concepts (i.e. before C++11) ;-) The latter has the big advantage that it works on each and every compiler that has been released in the last 20 years or so.

**Comment by hjmjohnson** [comment]
;-) .   Note that many of the C++ changes were focused on providing support for a more maintainable, robust code base.  My personal experience in ITK is that after *ONLY* supporting C++11 the codebase has become much less convoluted with different conditional compilations for different compilers.

Of course much of that benefit came from discarding new ITK feature support for old compilers (i.e. old versions of ITK continue to support old compiler, but new versions of ITK only support *new* (7 year old) compilers.

In my opinion, this is greatly accelerated the pace of development and re-invigorated the ITK community.

**Comment by hjmjohnson** [comment]
Outdated.

**Pull request closed without merging**
